apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-inference-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-inference
  template:
    metadata:
      labels:
        app: mnist-inference
    spec:
      containers:
      - name: mnist-inference
        image: inference_image
        ports:
        - containerPort: 80
